# GitHub Actions Workflow - Auto Update ERSE Data
# 
# This workflow automatically downloads the latest CSV data from ERSE
# and commits it to the repository monthly.
#
# Setup:
# 1. Copy this file to .github/workflows/update-erse.yml
# 2. Copy download-erse.js to scripts/download-erse.js
# 3. Push to GitHub
# 4. Enable Actions in repo settings if needed
#
# Manual trigger: Actions tab → "Update ERSE Data" → "Run workflow"

name: Update ERSE Data

on:
  schedule:
    # Runs at 09:00 UTC on day 5 of every month
    # Day 5 gives ERSE time to publish monthly data
    - cron: '0 9 5 * *'
  
  # Allows manual trigger from GitHub UI
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install dependencies
        run: |
          npm init -y
          npm install playwright
      
      - name: Install Chromium
        run: npx playwright install chromium
      
      - name: Download ERSE CSV
        run: node scripts/download-erse.js
      
      - name: Check for changes
        id: changes
        run: |
          git diff --quiet data/ || echo "changed=true" >> $GITHUB_OUTPUT
      
      - name: Commit and push
        if: steps.changes.outputs.changed == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/
          git commit -m "chore: update ERSE data $(date +%Y-%m)"
          git push
      
      - name: No changes detected
        if: steps.changes.outputs.changed != 'true'
        run: echo "No changes in CSV data"
